### ISSUE TITLE
Template folder not downloaded

### ISSUE THREAD

**Issue by Firerazer** [Karosieben/boblocale#139]
Hello,
I downloaded the project because I see that you added a template model for all files and I wanted to check with my code editor for differences. But the template folder is not downloaded... Do you have any idea?
Thanks a lot!
Best regards,
Firerazer

**Comment by Firerazer** [comment]
Addition : the En folder is not downloaded too...

**Comment by Karosieben** [comment]
This is correct, because these two folders arent needed in the build process, but it definitely works with git commands.
Anyway, I'll investigate.

**Comment by Karosieben** [comment]
Okay, following this documentation ( https://git-scm.com/docs/gitattributes ) the benaviour is intended.

However, you can pull the entire repo with the following git commands:
```
cd [your desired directory]
git clone https://github.com/Karosieben/boblocale.git
```

This will create a folder named "boblocale" with the entire repo in it, including the template and the english source files. You can also update the repo to the latest commit with `git pull` inside the boblocale folder.
