### ISSUE TITLE
Change Base Game names

### ISSUE THREAD

**Issue by Karosieben** [Karosieben/boblocale#146]
Hey there,

I just wanted to ask about your opinion regarding changes to base game names.

For example:
Bobs Logistics adds new Flying Robot Frames.
The Translation includes:

```
flying-robot-frame-2=Flying robot frame MK2
flying-robot-frame-3=Flying robot frame MK3
flying-robot-frame-4=Flying robot frame MK4
```

I personally translated also the base game string in the german translation:
```
flying-robot-frame=Flugrobotergestell 1
flying-robot-frame-2=Flugrobotergestell 2
flying-robot-frame-3=Flugrobotergestell 3
flying-robot-frame-4=Flugrobotergestell 4
```

I think, this improves the consistency of the translation and leaves the hint, that there are several robot frames in the game instead of just the one.

What's do you think, guys?

Regards from germany,
Karosieben

**Comment by Firerazer** [comment]
It's something that could be a smart addition I think, yes! It's something that is not only on robots frame I think
Approved!

**Comment by Karosieben** [comment]
Okay, I'll add the required translation strings to the template file with a comment.

**Comment by shirutan** [comment]
I agree with changing the Base names.
However, if there is a Base name, if you change it as follows, translation work will decrease。
Can not use this method if change the Base names.

```
flying-robot-frame-2=Flying robot frame MK2
flying-robot-frame-3=Flying robot frame MK3
flying-robot-frame-4=Flying robot frame MK4
```
↓
```
flying-robot-frame-2=__ITEM__flying-robot-frame__ MK2
flying-robot-frame-3=__ITEM__flying-robot-frame__ MK3
flying-robot-frame-4=__ITEM__flying-robot-frame__ MK4
```

However, this will be discussed at Bob's mods.

**Comment by Karosieben** [comment]
I dropped this change, because some eintities get generated by scripts an we ended up with some names like "Chemical Plant 1 1" and "Chemical Plant 1 2"...

So, let's stick with the more base-game-like thing of havin the first item named without any number or MK
