### ISSUE TITLE
Link to outdated mod

### ISSUE THREAD

**Issue by Firerazer** [Karosieben/boblocale#148]
You add a link to an outdated mod ;)
shinybob, https://mods.factorio.com/mod/ShinyBob
need to be changed to
shinybobGFX, https://mods.factorio.com/mods/Zombiee/ShinyBobGFX

**Comment by Karosieben** [comment]
Yea, I know. That's the mod, which originally was supported. I'll change it.

**Comment by Karosieben** [comment]
Done.
