### ISSUE TITLE
Issues in en locale boblogistics_0.16.7

### ISSUE THREAD

**Issue by burunduk** [Karosieben/boblocale#163]
bob-construction-robot-5=Fusion powered Construction robot MK**4**
bob-logistic-robot-5=Fusion powered Logistic robot MK**4**

**Comment by Karosieben** [comment]
I'll investigate, but the english source files come from bob himself. They're not part of this mod ;)

**Comment by burunduk** [comment]
And where is Bob's bug tracker?

**Comment by Karosieben** [comment]
In the forums: https://forums.factorio.com/viewtopic.php?f=51&t=54612

**Comment by Karosieben** [comment]
I'll update the source files immediately.

**Comment by Karosieben** [comment]
Well, I think, this can be closed now. Source files were updated.
