### ISSUE TITLE
Updated mod bobsflowcontrol-updated

### ISSUE THREAD

**Issue by burunduk** [Karosieben/boblocale#213]
bobsflowcontrol now have updaed version: [bobsflowcontrol-updated](https://mods.factorio.com/mod/bobsflowcontrol-updated)

**Comment by Karosieben** [comment]
Well.

The mod author already has some german translations done.
Maybe we should contact him/her to avoid conflicts.

**Comment by Karosieben** [comment]
I've added the source file.

However, i will not do a german translation, because the mod author already has supplies a german translation by himself.
