### ISSUE TITLE
Filter long in near inserter-Cannot translate

### ISSUE THREAD

**Issue by doxilos** [Karosieben/boblocale#59]
Is it supposed to mean: A near inserter with filtered long inserting but cannot filter near? or : Filter inserter with long inserting?

**Comment by Karosieben** [comment]
Well, I don't know either. Maybe you could boot up with bob's mods and activated inserters (config mod) and go into creative mode to check it.

**Comment by doxilos** [comment]
I found it while playing. It picks up 2 squares back and drops it 1 square front.
