### ISSUE TITLE
Add more bob's mods.

### ISSUE THREAD

**Issue by burunduk** [Karosieben/boblocale#88]
You can add other fashion-related modes bobs?
bobsflowcontrol
bobmods_gfxtweak
bob_presets
CMHMod

**Comment by Karosieben** [comment]
Of course, I will add them asap. :)

**Comment by Karosieben** [comment]
I added bobsflowcontrol, bobsmods_gfxtweak and both CMHMods, but I can't find bob_presets at the modportal. Could you provide a link? :)

**Comment by burunduk** [comment]
[mod portal](https://mods.factorio.com/mods/Ambaire/preset-for-bobs-ores)

**Comment by Karosieben** [comment]
Thanks. Added.
